"""
Email Sail Agent — Response Drafter Service

Drafts email responses using AI. Writes to Google Docs for user review.
"""

import logging
from datetime import datetime
from typing import Optional

import httpx

logger = logging.getLogger("email-sail.drafter")

GOOGLE_DOCS_API = "https://docs.googleapis.com/v1/documents"
GOOGLE_DRIVE_API = "https://www.googleapis.com/drive/v3/files"

# Tone templates
TONE_INSTRUCTIONS = {
    "professional": "Write in a professional, clear, and courteous tone. Be direct but warm.",
    "warm": "Write in a warm, friendly, and personal tone. Show genuine care and interest.",
    "direct": "Write in a concise, direct tone. Get to the point quickly. No fluff.",
    "empathetic": "Write in an empathetic, understanding tone. Acknowledge their situation first.",
}


def build_draft_prompt(
    subject: str,
    sender_name: str,
    email_body: str,
    category: str,
    tone: str = "professional",
    business_info: str = "",
) -> str:
    """Build the AI prompt for drafting a response."""
    tone_instruction = TONE_INSTRUCTIONS.get(tone, TONE_INSTRUCTIONS["professional"])

    category_context = {
        "customer_inquiry": "This is a customer inquiry. They're asking about your services or pricing. Be helpful and include a clear next step.",
        "booking_request": "This is a scheduling request. Propose specific times and make it easy to book.",
        "invoice_payment": "This is related to billing or payment. Be clear about amounts, due dates, and payment methods.",
        "urgent": "This is urgent. Acknowledge the urgency and provide a clear, immediate response.",
        "revenue_alert": "This is a revenue recovery situation. Be empathetic, not pushy. Offer help, not pressure.",
    }.get(category, "Respond helpfully and professionally.")

    prompt = f"""You are an email assistant helping respond to a business email.

{tone_instruction}

Context: {category_context}

{"Business context: " + business_info if business_info else ""}

--- INCOMING EMAIL ---
From: {sender_name}
Subject: {subject}
Body:
{email_body[:3000]}
--- END INCOMING ---

Write a professional email response. Include:
1. A personalized greeting
2. Direct response to their question/request
3. A clear next step or call to action
4. A professional sign-off

Keep it concise (under 200 words). Do NOT include placeholders like [Your Name] — write as if you are the business owner.

Response (HTML format, ready to send):
"""
    return prompt


async def draft_with_llm(prompt: str, access_token: str) -> str:
    """
    Draft response using an LLM.
    Tries Hermes/local first, falls back to configured provider.
    For now, returns a structured template draft.
    """
    # TODO: Integrate with tier router (Hermes local → Kimi → Claude)
    # For MVP, return a structured template that the user can edit

    # Extract key info from prompt for template
    lines = prompt.split("\n")
    sender = ""
    subject = ""
    for line in lines:
        if line.startswith("From:"):
            sender = line.replace("From:", "").strip()
        if line.startswith("Subject:"):
            subject = line.replace("Subject:", "").strip()

    # Generate a template draft
    draft = f"""<p>Hi {sender.split()[0] if sender else 'there'},</p>

<p>Thank you for your email regarding <strong>{subject}</strong>.</p>

<p>[Your response here — address their specific question or request]</p>

<p>[Next step — what should happen next?]</p>

<p>Best regards,<br>
[Your Name]</p>

<p><em>---</em><br>
<em>Draft generated by Email Sail Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}</em><br>
<em>Please review and edit before sending.</em></p>
"""
    return draft


async def create_google_doc(
    access_token: str,
    title: str,
    content: str,
) -> dict:
    """
    Create a Google Doc with the draft response.
    Returns: {"id": str, "url": str}
    """
    headers = {"Authorization": f"Bearer {access_token}"}

    async with httpx.AsyncClient() as client:
        # Create the document
        create_resp = await client.post(
            GOOGLE_DOCS_API,
            headers=headers,
            json={"title": title},
            timeout=30,
        )
        create_resp.raise_for_status()
        doc = create_resp.json()
        doc_id = doc["documentId"]

        # Insert content
        await client.post(
            f"{GOOGLE_DOCS_API}/{doc_id}:batchUpdate",
            headers=headers,
            json={
                "requests": [
                    {
                        "insertText": {
                            "location": {"index": 1},
                            "text": content,
                        }
                    }
                ]
            },
            timeout=30,
        )

        # Move to a folder (optional)
        # Set sharing permissions if needed

    return {
        "id": doc_id,
        "url": f"https://docs.google.com/document/d/{doc_id}/edit",
        "title": title,
    }


async def create_draft_in_docs(
    access_token: str,
    subject: str,
    sender_name: str,
    email_body: str,
    category: str,
    tone: str = "professional",
) -> dict:
    """
    Full pipeline: draft response → create Google Doc.
    Returns doc info + draft text.
    """
    # Build prompt
    prompt = build_draft_prompt(subject, sender_name, email_body, category, tone)

    # Generate draft
    draft_text = await draft_with_llm(prompt, access_token)

    # Create Google Doc
    today = datetime.now().strftime("%Y-%m-%d")
    doc_title = f"DRAFT: {subject} - {sender_name} - {today}"
    doc_info = await create_google_doc(access_token, doc_title, draft_text)

    return {
        "draft_text": draft_text,
        "doc_id": doc_info["id"],
        "doc_url": doc_info["url"],
        "doc_title": doc_info["title"],
    }
