"""
Email Sail Agent — Response Drafter Service

Drafts email responses using OpenRouter LLM.
Falls back to template if LLM is unavailable.
Writes drafts to Google Docs for user review.
"""

import logging
from datetime import datetime

import httpx

from api.services.llm_service import get_llm_service, OpenRouterError

logger = logging.getLogger("email-sail.drafter")

GOOGLE_DOCS_API = "https://docs.googleapis.com/v1/documents"


async def create_google_doc(
    access_token: str,
    title: str,
    content: str,
) -> dict:
    """
    Create a Google Doc with the draft response.
    Returns: {"id": str, "url": str, "title": str}
    """
    headers = {"Authorization": f"Bearer {access_token}"}

    async with httpx.AsyncClient() as client:
        # Create the document
        create_resp = await client.post(
            GOOGLE_DOCS_API,
            headers=headers,
            json={"title": title},
            timeout=30,
        )
        create_resp.raise_for_status()
        doc = create_resp.json()
        doc_id = doc["documentId"]

        # Insert content
        await client.post(
            f"{GOOGLE_DOCS_API}/{doc_id}:batchUpdate",
            headers=headers,
            json={
                "requests": [
                    {
                        "insertText": {
                            "location": {"index": 1},
                            "text": content,
                        }
                    }
                ]
            },
            timeout=30,
        )

    return {
        "id": doc_id,
        "url": f"https://docs.google.com/document/d/{doc_id}/edit",
        "title": title,
    }


async def create_draft_in_docs(
    access_token: str,
    subject: str,
    sender_name: str,
    sender_email: str,
    email_body: str,
    category: str,
    tone: str = "professional",
    business_info: str = "",
    tier: str = "cheap",
    preferred_model: str = None,
    user_name: str = "",
) -> dict:
    """
    Full pipeline: generate AI draft → create Google Doc.

    Returns: {
        "draft_text": str,
        "doc_id": str,
        "doc_url": str,
        "doc_title": str,
        "model_used": str,
        "ai_generated": bool,
    }
    """
    llm = get_llm_service()
    draft_text = None
    model_used = "template"
    ai_generated = False

    logger.info(f"LLM service configured: {llm.is_configured}, key present: {bool(llm.api_key)}")

    # Try AI draft first
    if llm.is_configured:
        try:
            result = await llm.draft_email_response(
                subject=subject,
                sender_name=sender_name,
                sender_email=sender_email,
                email_body=email_body,
                category=category,
                tone=tone,
                business_info=business_info,
                tier=tier,
                preferred_model=preferred_model,
                user_name=user_name,
            )
            draft_text = result["text"]
            model_used = result.get("model", "unknown")
            ai_generated = True
            logger.info(f"AI draft generated: model={model_used}")
        except OpenRouterError as e:
            logger.warning(f"LLM draft failed: {e}")
        except Exception as e:
            logger.error(f"Unexpected LLM error: {e}")

    # Fallback to template
    if draft_text is None:
        first_name = sender_name.split()[0] if sender_name else "there"
        draft_text = (
            f"<p>Hi {first_name},</p>\n\n"
            f"<p>Thank you for your email regarding <strong>{subject}</strong>.</p>\n\n"
            f"<p>[Your response here — address their specific question or request]</p>\n\n"
            f"<p>[Next step — what should happen next?]</p>\n\n"
            f"<p>Best regards,<br>[Your Name]</p>\n\n"
            f"<p><em>---</em><br>"
            f"<em>Draft generated by Email Sail Agent on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')}</em><br>"
            f"<em>Please review and edit before sending.</em></p>"
        )

    # Create Google Doc
    today = datetime.now().strftime("%Y-%m-%d")
    doc_title = f"DRAFT: {subject} - {sender_name} - {today}"
    doc_info = await create_google_doc(access_token, doc_title, draft_text)

    return {
        "draft_text": draft_text,
        "doc_id": doc_info["id"],
        "doc_url": doc_info["url"],
        "doc_title": doc_info["title"],
        "model_used": model_used,
        "ai_generated": ai_generated,
    }
