"""
Email Sail Agent — Twilio SMS + Voice Service
"""

import logging
from typing import Optional

from api.config import settings

logger = logging.getLogger("email-sail.twilio")


class TwilioService:
    def __init__(self, account_sid: str = None, auth_token: str = None, from_number: str = None):
        self.account_sid = account_sid or settings.TWILIO_ACCOUNT_SID
        self.auth_token = auth_token or settings.TWILIO_AUTH_TOKEN
        self.from_number = from_number or settings.TWILIO_PHONE_NUMBER

    @property
    def is_configured(self) -> bool:
        return bool(self.account_sid and self.auth_token and self.from_number)

    async def send_sms(self, to_number: str, body: str) -> dict:
        """Send an SMS message."""
        if not self.is_configured:
            raise ValueError("Twilio not configured. Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, and TWILIO_PHONE_NUMBER.")

        import httpx

        url = f"https://api.twilio.com/2010-04-01/Accounts/{self.account_sid}/Messages.json"
        auth = (self.account_sid, self.auth_token)

        async with httpx.AsyncClient() as client:
            resp = await client.post(
                url,
                auth=auth,
                data={
                    "To": to_number,
                    "From": self.from_number,
                    "Body": body[:1600],  # Twilio limit
                },
                timeout=30,
            )
            resp.raise_for_status()
            result = resp.json()

        logger.info("SMS sent to %s: %s", to_number, result.get("sid"))
        return {
            "sid": result.get("sid"),
            "status": result.get("status"),
            "to": to_number,
            "body": body,
        }

    async def make_call(
        self,
        to_number: str,
        twiml: str = None,
        url: str = None,
    ) -> dict:
        """
        Make a phone call.
        Either `twiml` (inline TwiML) or `url` (TwiML URL) must be provided.
        """
        if not self.is_configured:
            raise ValueError("Twilio not configured.")

        import httpx

        call_url = f"https://api.twilio.com/2010-04-01/Accounts/{self.account_sid}/Calls.json"
        auth = (self.account_sid, self.auth_token)

        data = {"To": to_number, "From": self.from_number}
        if twiml:
            data["Twiml"] = twiml
        elif url:
            data["Url"] = url
        else:
            # Default: simple greeting
            data["Twiml"] = (
                '<?xml version="1.0" encoding="UTF-8"?>'
                '<Response>'
                '<Say voice="Polly.Joanna">Hello, this is a call from your business assistant. '
                'Please hold while we connect you.</Say>'
                '</Response>'
            )

        async with httpx.AsyncClient() as client:
            resp = await client.post(call_url, auth=auth, data=data, timeout=30)
            resp.raise_for_status()
            result = resp.json()

        logger.info("Call placed to %s: %s", to_number, result.get("sid"))
        return {
            "sid": result.get("sid"),
            "status": result.get("status"),
            "to": to_number,
        }

    def generate_call_script(self, customer_name: str, purpose: str, key_points: list[str] = None) -> str:
        """Generate a call script for the user to follow."""
        script = f"""CALL SCRIPT
============
Customer: {customer_name}
Purpose: {purpose}

OPENING:
"Hi {customer_name}, this is [Your Name] from [Your Business]. Do you have a quick moment?"

KEY POINTS:
"""
        if key_points:
            for i, point in enumerate(key_points, 1):
                script += f"  {i}. {point}\n"
        else:
            script += "  [Add your talking points here]\n"

        script += """
CLOSING:
"Is there anything else I can help you with? Thanks for your time!"

---
Generated by Email Sail Agent
"""
        return script

    @staticmethod
    def format_sms_draft(customer_name: str, message_type: str = "follow_up") -> str:
        """Format an SMS draft based on message type."""
        templates = {
            "follow_up": f"Hi {customer_name}, just following up on my email. Let me know if you have any questions!",
            "appointment_reminder": f"Hi {customer_name}, this is a reminder about our upcoming appointment. Reply CONFIRM to confirm or RESCHEDULE to change.",
            "revenue_recovery": f"Hi {customer_name}, I noticed you didn't complete your purchase. Is there anything I can help with? Here's the link: [link]",
            "thank_you": f"Hi {customer_name}, thank you for your business! It's great working with you.",
        }
        return templates.get(message_type, templates["follow_up"])
